version: '3.8'
services:

  # app:
  #   build: proxy
  #   ports: 
  #     - 80:80
  #   depends_on:
  #     - api
  #   restart: always

  # portfolio:
  #   build: portfolio # Location of our Dockerfile
  #   ports:
  #     - 4200:4200 # Port mapping
  #   volumes:
  #     - /usr/local/app
  #   networks:
  #     - backend
  #   depends_on:
  #     - api
  #   restart: always

  api:
    image: portfolio-api
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app
    depends_on:
      - db
    networks:
      - backend
    restart: always

  db:
    image: 'mongo'
    # environment:
    #   - MONGODB_USERNAME=okteto
    #   - MONGODB_PASSWORD=mongodb123
    #   - MONGODB_DATABASE=okteto
    #   - MONGODB_ROOT_PASSWORD=mongodb123root
    #   - MONGODB_SYSTEM_LOG_VERBOSITY=0
    #   - MONGODB_DISABLE_SYSTEM_LOG=no
    #   - MONGODB_ENABLE_IPV6=no
    #   - MONGODB_ENABLE_DIRECTORY_PER_DB=no
    ports:
      - 27017:27017
    volumes:
      - data:/bitnami/mongodb
    restart: always
    networks:
      - backend

volumes:
  data:

networks:
  backend:
    driver: bridge
